server:
  register:
    host: 127.0.0.1
    port: 8090
  gateway:
    sync:
      host: 127.0.0.1
      start_port: 3310
    server:
      host: 127.0.0.1
      port: 8080
  worker:
    host: 127.0.0.1
    port: 9090
  web:
    host: 127.0.0.1
    port: 80




